services:
  - type: web
    name: move-quote
    runtime: node
    plan: starter
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SLACK_BOT_TOKEN
        sync: false
      - key: SLACK_SIGNING_SECRET
        sync: false
      - key: SLACK_APP_TOKEN
        sync: false
